import { readFileSync } from 'node:fs';
import { describe, it, expect, vi, afterEach } from 'vitest';
import { validateCompanySummary, COMPANY_SUMMARY_ENDPOINT } from './myscube-company-summary.mjs';
import { createMyscubeLiveApiAdapter } from './myscube-live-api.mjs';
const fixture = name => JSON.parse(readFileSync(new URL(`./fixtures/company-summary/${name}.json`, import.meta.url)));
const inputFor = data => ({ yearMonth: data.period.yearMonth, ...(data.period.weekNo ? { weekNo: data.period.weekNo } : {}) });
const context = { tenantId: 'mysc', actorId: 'admin-fixture', actorRole: 'admin' };
const env = { WORKBENCH_MYSCUBE_LIVE_ENABLED: 'true', WORKBENCH_MYSCUBE_COMPANY_SUMMARY_ENABLED: 'true' };
const setup = (options = {}) => {
  const adapter = createMyscubeLiveApiAdapter({ env, credentialProvider: async () => 'Bearer synthetic-only', resolveDns: async () => [{ address: '8.8.8.8', family: 4 }], transport: async () => fixture('month'), ...options });
  return { adapter, invoke: (input = inputFor(fixture('month')), signal) => adapter.invoke(context, COMPANY_SUMMARY_ENDPOINT.id, 1, input, { authorize: async () => {}, signal }) };
};
afterEach(() => vi.useRealTimers());
describe('company summary registered read contract', () => {
  it.each(['month', 'week', 'partial'])('accepts %s generated by the real BFF with synthetic emulator records', name => {
    const raw = fixture(name); expect(validateCompanySummary(raw, inputFor(raw))).toBe(raw);
    if (name === 'partial') { expect(raw.totalsScope).toBe('PARTIAL_REGISTERED_PROJECTS'); expect(raw.totals.actual.inflow.value).toBeNull(); }
  });
  it('does not advertise the new route until separately enabled, preserving both v1 hashes', () => {
    const old = setup({ env: { WORKBENCH_MYSCUBE_LIVE_ENABLED: 'true' } }).adapter.list(context).items;
    const enabled = setup().adapter.list(context).items;
    expect(old).toHaveLength(2); expect(enabled).toHaveLength(3); expect(enabled.slice(0, 2)).toEqual(old);
    expect(setup({ env: { WORKBENCH_MYSCUBE_COMPANY_SUMMARY_ENABLED: 'true' } }).adapter.list(context).items).toEqual([]);
  });
  it.each([
    data => { data.period.yearMonth = '2026-10'; },
    data => { data.catalogComplete = !data.catalogComplete; },
    data => { data.counts.failed++; },
    data => { data.rows.push(structuredClone(data.rows[0])); data.catalog.eligibleCount = data.catalog.enumeratedCount = data.catalog.knownTotal = data.counts.eligible = 2; },
    data => { data.totals.actual.inflow.partialValue++; },
    data => { data.weeks[0].weekCalendarUniform = false; },
    data => { data.readWindow.atomicSnapshot = true; },
    data => { data.totals.actual.inflow.value = 0; data.totals.actual.inflow.complete = false; },
  ])('rejects inconsistent scope, values or calendars', sabotage => {
    const raw = fixture('month'); const input = inputFor(raw); sabotage(raw); expect(() => validateCompanySummary(raw, input)).toThrow();
  });
  it('sends only the fixed GET path and verified period, marks partial evidence as truncated', async () => {
    const raw = fixture('partial'), transport = vi.fn(async () => raw); const { invoke } = setup({ transport });
    const result = await invoke(inputFor(raw)); expect(result.truncated).toBe(true);
    expect(result.metadata).toMatchObject({ sourceKind: 'myscube-live', companySummary: true, resultScope: 'PARTIAL_REGISTERED_PROJECTS' });
    expect(transport.mock.calls[0][0].url.pathname).toBe('/api/v1/company-cashflow-summary');
    for (const bad of [{ yearMonth: '2026-09', weekNo: 0 }, { yearMonth: '2026-09', weekNo: '1' }, { yearMonth: '2026-09', after: 'page2' }]) await expect(invoke(bad)).rejects.toMatchObject({ statusCode: 400 });
    expect(transport).toHaveBeenCalledTimes(1);
  });
  it('allows a company response beyond ten seconds, without retaining settled authorization errors', async () => {
    vi.useFakeTimers(); const transport = vi.fn(() => new Promise(resolve => setTimeout(() => resolve(fixture('month')), 20000)));
    const { invoke } = setup({ transport }); const pending = invoke(); await vi.advanceTimersByTimeAsync(20000); await expect(pending).resolves.toHaveProperty('data');
    const failure = setup({ transport: async () => { throw Object.assign(new Error('denied'), { statusCode: 403 }); } });
    for (let i = 0; i < 3; i++) await expect(failure.invoke()).rejects.toMatchObject({ statusCode: 403 });
  });
  it('keeps the 55-second adapter deadline finite and relies on the dedicated BFF admission after settlement', async () => {
    vi.useFakeTimers(); const pending = setup({ transport: ({ signal }) => new Promise((_resolve, reject) => signal.addEventListener('abort', () => reject(signal.reason))) });
    const result = expect(pending.invoke()).rejects.toMatchObject({ statusCode: 504 }); await vi.advanceTimersByTimeAsync(55000); await result;
    // A second request reaches transport instead of a six-minute shared AXR cooldown.
    const abort = new AbortController(); const second = expect(pending.invoke(undefined, abort.signal)).rejects.toMatchObject({ statusCode: 504 }); abort.abort(); await second;
  });
});
