import React, { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { SourcePreview } from '../src/app/components/product-operations/html-preview/SourcePreview';
import { ConversationPanel } from './ConversationPanel';
import { BoundEvidence } from './BoundEvidence';
import { RecoveryPanel } from './RecoveryPanel';
import { auth, demo, login, logout, request, subscribe } from './client';
import './studio.css';

const OperationsPanel = lazy(() => import('./OperationsPanel').then((module) => ({ default: module.OperationsPanel })));
const ReactStudio = lazy(() => import('./ReactStudio').then((module) => ({ default: module.ReactStudio })));

type Source = { title: string; html: string };
type DataBinding = { template: Source; bindings: Record<string, { evidenceId: string; kind: 'table' | 'value'; column?: string; row?: number }> };
type PreviewResult = { previewHtml: string; previewHash: string; css?: string; cssHash?: string; runtimeVersion?: string };
type PreviewState = PreviewResult & { sourceHtml: string };
type Revision = { dataBinding?: DataBinding; id: string; version: number; source: Source; contentHash: string; updatedAt: string; updatedBy: string; referenceIds: string[]; title?: string; previewHtml?: string; previewHash?: string; css?: string; cssHash?: string; runtimeVersion?: string };
type PageSummary = Omit<Revision, 'source'> & { title: string };
type Reference = { id: string; title: string; url: string | null; guidance: string };
const empty = { title: '새 업무 화면', html: '' };
const time = (value: string) => new Date(value).toLocaleString('ko-KR');

function download(name: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function savedPreview(value: Revision): PreviewState | null { return value.previewHtml && value.previewHash ? { sourceHtml: value.source.html, previewHtml: value.previewHtml, previewHash: value.previewHash, css: value.css, cssHash: value.cssHash, runtimeVersion: value.runtimeVersion } : null; }

function Studio() {
  const editorTarget = useRef(0);
  const [dataBinding, setDataBinding] = useState<DataBinding | undefined>();
  const [pages, setPages] = useState<PageSummary[]>([]); const [saved, setSaved] = useState<Revision | null>(null); const [source, setSource] = useState<Source>(empty);
  const [references, setReferences] = useState<Reference[]>([]); const [selectedRefs, setSelectedRefs] = useState<string[]>([]); const [example, setExample] = useState('');
  const [history, setHistory] = useState<PageSummary[]>([]); const [proposal, setProposal] = useState<{ source: Source; referenceIds: string[] } | null>(null); const [review, setReview] = useState<{ files: Record<string, string> } | null>(null);
  const [prompt, setPrompt] = useState('현금흐름 현황을 넓은 요약 영역과 프로젝트별 표로 구성해 주세요. 작은 화면에서는 한 열로 보여 주세요. 연결되지 않은 수치는 확인 필요로 표시해 주세요.');
  const [preview, setPreview] = useState<PreviewState | null>(null); const [activeCanvas, setActiveCanvas] = useState<'preview' | 'source'>('source'); const [hash, setHash] = useState('');
  const [busy, setBusy] = useState(false); const [modelEnabled, setModelEnabled] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const dirty = saved ? JSON.stringify(source) !== JSON.stringify(saved.source) || JSON.stringify(selectedRefs) !== JSON.stringify(saved.referenceIds)
    : source.title !== empty.title || source.html !== example || JSON.stringify(selectedRefs) !== JSON.stringify(references.map((item) => item.id));
  const previewStale = Boolean(preview && preview.sourceHtml !== source.html);
  useEffect(() => { let active = true; void crypto.subtle.digest('SHA-256', new TextEncoder().encode(source.html)).then((bytes) => { if (active) setHash(Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, '0')).join('')); }); return () => { active = false; }; }, [source.html]);
  useEffect(() => { let active = true; setBusy(true); void Promise.all([request('/capabilities'), request(''), request('/references')]).then(([capabilities, list, refs]) => { if (!active) return; setModelEnabled(capabilities.modelEnabled); setMessage(capabilities.message); setPages(list.items); setReferences(refs.references); setSelectedRefs(refs.references.map((item: Reference) => item.id)); setExample(refs.example); setSource({ title: '새 업무 화면', html: refs.example }); }).catch((reason) => { if (active) setError(reason.message); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, []);
  const run = async (operation: () => Promise<void>) => { setBusy(true); setError(''); try { await operation(); } catch (reason) { setError(reason instanceof Error ? reason.message : '처리를 완료하지 못했습니다.'); } finally { setBusy(false); } };
  const load = (value: Revision) => { editorTarget.current++; setSaved(value); setDataBinding(value.dataBinding ? { template: value.dataBinding.template, bindings: value.dataBinding.bindings } : undefined); setSource(value.source); setSelectedRefs(value.referenceIds); setHistory([]); setReview(null); setProposal(null); setPreview(savedPreview(value)); setActiveCanvas(value.previewHtml ? 'preview' : 'source'); };
  const remember = (value: Revision) => { load(value); setPages((items) => [{ ...value, title: value.source.title }, ...items.filter((item) => item.id !== value.id)]); };
  const mayLeave = () => !dirty || window.confirm('저장하지 않은 소스 변경이 있습니다. 변경을 버리고 이동할까요?');
  const applyPreview = () => void run(async () => { const result = await request('/preview', 'POST', { source }) as PreviewResult; setPreview({ ...result, sourceHtml: source.html }); setActiveCanvas('preview'); setMessage('현재 HTML 원문으로 안전한 미리보기를 적용했습니다. 저장·리뷰 완료와는 별도입니다.'); });
  const save = () => void run(async () => { const result = await request(saved ? `/${saved.id}` : '', saved ? 'PUT' : 'POST', { expectedVersion: saved?.version || 0, source, referenceIds: selectedRefs, ...(dataBinding ? { dataBinding } : {}) }); remember(result); setMessage(`버전 ${result.version}으로 저장했습니다. ${time(result.updatedAt)}`); });
  return <div className="studio">
    <header className="studio-header"><div className="brand"><span className="eyebrow">MYSCube · AXR</span><h1>HTML 제작 공간</h1><p>원문을 직접 편집하고, 안전한 실행본과 저장 버전을 분리해 확인합니다.</p></div><div className="header-actions"><a className="quiet" href="/?mode=operations" target="_blank" rel="noopener noreferrer">운영 기록 ↗</a><a className="quiet" href="/?mode=react">업무 공간</a><span className="save-state" role="status">{busy ? '처리 중…' : dirty ? '저장하지 않은 변경' : saved ? `저장됨 · 버전 ${saved.version}` : '새 화면 · 아직 저장하지 않음'}</span><button className="quiet" disabled={busy} onClick={applyPreview}>미리보기 적용</button><button disabled={busy} onClick={save}>현재 소스 저장</button>{!demo && <button className="quiet" disabled={busy} onClick={() => void logout()}>로그아웃</button>}</div></header>
    <RecoveryPanel scope="html-page" disabled={busy} targetKey={String(editorTarget.current)} onRecovered={(value) => { if (!value || typeof value !== 'object' || !('id' in value) || !('source' in value) || typeof (value as Revision).source?.html !== 'string' || !mayLeave()) return false; load(value as Revision); setMessage('확인한 HTML 저장 결과를 불러왔습니다.'); return true; }} />
    {message && <p className="notice" role="status">{message}</p>}{error && <p className="error" role="alert">{error}</p>}
    <div className="workspace"><aside className="library" aria-label="저장한 화면"><div className="section-heading"><div><p className="section-kicker">PAGES</p><h2>저장한 화면</h2></div><button className="quiet compact" disabled={busy} onClick={() => { if (mayLeave()) { editorTarget.current++; setSaved(null); setDataBinding(undefined); setSelectedRefs(references.map((item) => item.id)); setSource({ ...empty, html: example }); setHistory([]); setProposal(null); setReview(null); setPreview(null); setActiveCanvas('source'); } }}>새 화면</button></div>{!pages.length && <p className="subtle">처음 저장한 화면부터 여기에 표시됩니다.</p>}{pages.map((item) => <button className={`page-item ${saved?.id === item.id ? 'selected' : ''}`} disabled={busy} key={item.id} onClick={() => { if (mayLeave()) void run(async () => load(await request(`/${item.id}`))); }}><strong>{item.title}</strong><small>버전 {item.version} · {time(item.updatedAt)}</small></button>)}</aside>
      <main className="studio-main"><section className="canvas-panel" aria-label="HTML 캔버스"><div className="canvas-toolbar"><div className="canvas-tabs" role="tablist" aria-label="작업 캔버스 보기"><button className={activeCanvas === 'preview' ? 'active' : ''} role="tab" aria-selected={activeCanvas === 'preview'} onClick={() => setActiveCanvas('preview')}>미리보기</button><button className={activeCanvas === 'source' ? 'active' : ''} role="tab" aria-selected={activeCanvas === 'source'} onClick={() => setActiveCanvas('source')}>소스</button></div><div className="canvas-meta"><span className="badge">외부 통신 차단</span>{preview && <span className={previewStale ? 'stale-state' : 'fresh-state'}>{previewStale ? '소스 변경됨' : '현재 소스 확인됨'}</span>}</div></div>
        <BoundEvidence bindings={dataBinding?.bindings} />
        {activeCanvas === 'preview' ? <div className="preview-stage">{previewStale && <p className="notice">편집한 원문이 마지막 미리보기와 다릅니다. 상단의 ‘미리보기 적용’을 눌러 현재 원문을 확인해 주세요.</p>}{preview ? <SourcePreview html={preview.previewHtml} artifact={{ expectedHash: preview.previewHash }} /> : <div className="preview-empty"><strong>아직 적용한 미리보기가 없습니다.</strong><span>원문을 작성한 뒤 상단의 ‘미리보기 적용’을 눌러 확인해 주세요.</span></div>}</div> : <div className="source-stage"><div className="section-heading"><div><p className="section-kicker">SOURCE</p><h2>HTML 원문</h2></div><span className="badge">{dirty ? '저장하지 않은 변경' : saved ? `저장 버전 ${saved.version}` : '새 문서'}</span></div><fieldset disabled={busy}><label>화면 제목<input value={source.title} onChange={(event) => { setDataBinding(undefined); setSource({ ...source, title: event.target.value }); setReview(null); }} maxLength={80} /></label><label>HTML 원문<textarea className="code" spellCheck={false} value={source.html} onChange={(event) => { setDataBinding(undefined); setSource({ ...source, html: event.target.value }); setReview(null); }} /></label></fieldset><p className="hash">편집 원문 SHA-256: {hash}</p><p className="subtle">{dataBinding ? '조회 근거와 연결된 화면입니다. 저장할 때 같은 자료인지 다시 확인합니다.' : '직접 편집한 원문입니다. 입력한 업무 수치를 검증한 자료로 표시하지 않습니다.'}</p></div>}</section>
        <aside className="studio-rail"><ConversationPanel modelEnabled={modelEnabled} busy={busy} currentSource={source} onProposal={(next) => { setSource({ title: next.title, html: next.html }); setSelectedRefs(Array.isArray(next.referenceIds) ? next.referenceIds as string[] : []); setDataBinding(next.template && next.bindings ? { template: next.template, bindings: next.bindings } as DataBinding : undefined); setProposal(null); setReview(null); setMessage('대화 제안을 편집기에 적용했습니다. 미리보기와 저장을 이어서 확인해 주세요.'); }} /><section className="side-panel" aria-label="제작 요청과 참고 자료"><div className="section-heading"><div><p className="section-kicker">MAKE</p><h2>요청과 참고 자료</h2></div><span className="badge">{modelEnabled ? 'AI 연결됨' : '직접 편집 가능'}</span></div><fieldset disabled={busy}><label>화면 요청<textarea className="prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} /></label><details className="reference-disclosure"><summary>생성에 참고할 레퍼런스 · {selectedRefs.length}개</summary><div className="references">{references.map((reference) => <label key={reference.id} className="reference"><input type="checkbox" checked={selectedRefs.includes(reference.id)} onChange={(event) => setSelectedRefs((ids) => event.target.checked ? [...ids, reference.id] : ids.filter((id) => id !== reference.id))} /><span><strong>{reference.title}</strong><small>{reference.guidance}</small>{reference.url && <a href={reference.url} target="_blank" rel="noopener noreferrer">공식 문서 보기 ↗</a>}</span></label>)}</div></details><div className="stacked-actions"><button disabled={!modelEnabled} onClick={() => void run(async () => { const result = await request('/generate', 'POST', { prompt, currentHtml: source.html || undefined, referenceIds: selectedRefs }); setProposal(result); setMessage('HTML 제안이 생성되었습니다. 검토 후 적용해 주세요. 아직 저장되지 않았습니다.'); })}>HTML 생성·수정 요청</button><p className="subtle">{modelEnabled ? '현재 소스와 선택한 참고 자료를 함께 전달합니다.' : 'AI 연결 전에도 HTML을 직접 수정하고 미리보기·저장·복원을 사용할 수 있습니다.'}</p></div></fieldset>{proposal && <div className="proposal"><h3>생성된 HTML 제안</h3><pre data-testid="proposed-html">{proposal.source.html}</pre><div className="actions"><button disabled={busy} onClick={() => { setDataBinding(undefined); setSource(proposal.source); setSelectedRefs(proposal.referenceIds); setProposal(null); setReview(null); setMessage('편집기에 적용했습니다. 미리보기와 저장을 이어서 확인해 주세요.'); }}>이 소스 적용</button><button className="quiet" disabled={busy} onClick={() => setProposal(null)}>제안 닫기</button></div></div>}</section>
          <section className="side-panel" aria-label="버전과 검토"><div className="section-heading"><div><p className="section-kicker">REVIEW</p><h2>버전과 검토</h2></div></div><div className="rail-actions">{saved && <button className="quiet" disabled={busy} onClick={() => void run(async () => { const result = await request(`/${saved.id}/versions`); setHistory(result.items); })}>버전 이력</button>}{saved && <button className="quiet" disabled={busy || dirty} onClick={() => void run(async () => setReview(await request(`/${saved.id}/review?version=${saved.version}`)))}>저장 버전 리뷰·내보내기</button>}</div>{history.length > 0 && <div className="history"><h3>소스 버전 이력</h3>{history.map((item) => <div className="history-row" key={item.version}><span><strong>버전 {item.version}</strong><small>{time(item.updatedAt)} · {item.contentHash.slice(0, 12)}</small></span><button className="quiet compact" disabled={busy || item.version === saved?.version} onClick={() => { if (mayLeave()) void run(async () => { const result = await request(`/${saved!.id}/restore`, 'POST', { expectedVersion: saved!.version, version: item.version }); remember(result); setMessage(`버전 ${item.version}을 새 버전 ${result.version}으로 복원했습니다.`); }); }}>복원</button></div>)}</div>}{review && !dirty && <div className="review"><h3>리뷰 대상: 저장 버전 {saved?.version}</h3><p>저장된 원문과 실행본을 내려받아 Git에서 비교할 수 있습니다. 자동 커밋·PR·배포를 의미하지 않습니다.</p>{Object.entries(review.files).map(([name, content]) => <details key={name}><summary>{name}</summary><pre>{content}</pre><button className="quiet compact" onClick={() => download(name, content)}>{name} 다운로드</button></details>)}</div>}</section></aside>
      </main></div>
  </div>;
}
function App() { const [actorId, setActorId] = useState<string | null>(null); const [error, setError] = useState(''); useEffect(() => subscribe(setActorId), []); if (!actorId) return <main className="welcome"><span className="eyebrow">MYSCube · AXR</span><h1>나의 업무 공간</h1><p>업무 자료를 묻고, 필요한 화면을 만들며, 저장한 작업을 이어가세요.</p><button disabled={!auth} onClick={() => void login().catch((reason) => setError(reason.message))}>Google 계정으로 로그인</button>{!auth && <p>독립 제작 공간의 로그인 연결 설정이 필요합니다.</p>}{error && <p role="alert">{error}</p>}</main>; return new URLSearchParams(location.search).get('mode') === 'operations' ? <Suspense fallback={<p role="status">운영 기록 화면을 준비하고 있습니다…</p>}><OperationsPanel key={actorId} /></Suspense> : new URLSearchParams(location.search).get('mode') !== 'html' ? <Suspense fallback={<p role="status">업무 공간을 준비하고 있습니다…</p>}><ReactStudio key={actorId} /></Suspense> : <Studio key={actorId} />; }
createRoot(document.getElementById('root')!).render(<App />);
