apiVersion: v1
kind: Service
metadata:
  name: mysc-bff
  labels:
    app.kubernetes.io/name: mysc-bff
    app.kubernetes.io/part-of: inner-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysc-bff
  ports:
    - name: http
      port: 8080
      targetPort: http
