apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysc-bff
  labels:
    app.kubernetes.io/name: mysc-bff
    app.kubernetes.io/part-of: inner-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysc-bff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysc-bff
        app.kubernetes.io/part-of: inner-platform
    spec:
      containers:
        - name: bff
          image: inner-platform-bff:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: mysc-bff-env
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
